name: course-recsys
channels:
  - defaults
dependencies:
  - python=3.10
  - jupyterlab=3.5.2
  - scikit-learn=1.2.0
  - plotly=5.9.0
  - pandas=1.5.2
  - numpy=1.23.5
  - seaborn=0.12.2
  - tqdm=4.64.1
  - pip=22.3.1
  - pip:
    - tensorflow==2.11.0
    - PyYaml==6.0
    - widgetsnbextension==4.0.5
    - ipywidgets==8.0.4